### ISSUE TITLE
Changing SQL backend to mssql from sqlite3

### ISSUE THREAD

**Issue by aaroncalderon** [apollostack/GitHunt-API#24]
OS: Windows 7 32-bit
npm@3.10.3
node@v6.5.0

I was able to change the backend from sqlite3 to mssql, my `knexfile.js` looks like this:

```javascript
// Since Knex always runs this file first, all of our seeds and migrations are babelified.
require('babel-register');

module.exports = {
  development: {
    client: 'mssql',
    connection: {
      host : 'server',
      user : 'userName',
      password : 'P@$$w0rd',
      database : 'dbname'
    },
    useNullAsDefault: true,
  },
};
```

and changed [`seed.js#L87-L88`](https://github.com/apollostack/GitHunt-API/blob/master/seeds/seed.js#L87-L88) to: 

```javascript
        created_at: new Date(Date.now() - i * 10000).toISOString(),
        updated_at: new Date(Date.now() - i * 10000).toISOString(),
```

However, on [`seed.js#L91`](https://github.com/apollostack/GitHunt-API/blob/master/seeds/seed.js#L92)  I get an error:

```
      }).then(([id]) => { // <= here
        repoIds[repository_name] = id;
      });
    }));
```

I have narrowed it down to `mssql` returning null values, on the other hand, sqlite3 returns the row id (I think).

Any ideas? I am currently researching if there is a way to change `mssql` behaviour but have not found anything so far.

**Comment by aaroncalderon** [comment]
# Update

I got it. To solve __this__ issue, I added `.returning('id')` on [`seed.js#86`](https://github.com/apollostack/GitHunt-API/blob/master/seeds/seed.js#L86) 

```javascript
      return knex('entries').returning('id').insert({
```

I found some other issues which are out of the scope of conversation, like:

With my modification to the `create_at` and `updated_at` insertion make it ivalid format for graphql type `TypeError: Float cannot represent non numeric value: 2016-09-23T17:02:47.319Z`.

There are other issues with some queries that are invalid for MSSQL dbs. e.g. `RequestError: select top (@p0) [entries].*, SUM(votes.vote_value) as score from [entries] left join [votes] on [entries].[id] = [votes].[entry_id] group by [entries].[id] order by [score] desc - Column 'entries.created_at' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.`

But, that is something to look into later.

Will be closing this issue now.

**Comment by helfer** [comment]
Yeah, unfortunately it's not possible with knex to just transparently switch the backing DB. You'd figure that since it's an abstraction on top of any SQL DB it would do that, but it doesn't...

**Comment by aaroncalderon** [comment]
I may look further into this or maybe explore using `sequelize` since it is being used succesfully on the apollo-tutorial-kit.

I think the complexity of the queries on the __apollo-tutorial-kit__ is lower compared to __GitHunt-API__, so I do not know what issues I may encounter if I give it a go.

Thanks for your reply.

**Comment by stubailo** [comment]
@aaroncalderon if you can migrate this repository to Sequelize, I'd be very thankful!

**Comment by ezytools** [comment]
Coincidentally I have been running it in PostgreSQL and thought I'd leave me feeback here for anyone interested.

1.  Add .returning("id") to the insert statements (even the migrations file).
2.  Dates are a problem.  Likewise I was disappointed knex didn't do the translation properly.  My solution was to use "whereRaw" i.e:
              .whereRaw('updated_at > now()- interval \'1 hour\'')
     IMO if it's not going to be abstracted properly better to be obviously and clearly not portable.
And:
            .insert({
              created_at: 'now()',
              updated_at: 'now()',
3. Label the count in getCommentCount:
               .count('id as CNT');
               return query.then(rows => rows.map(row => (row['CNT'] || '0')));

Otherwise pretty painless to get it working with postgres.

Thanks for the great demo app :)

**Comment by stubailo** [comment]
Thanks! Yeah it's frustrating that knex doesn't handle the differences, but I guess it makes sense since it's just a query builder. If anyone wants to send a PR to move to a more fully featured ORM that could be great.
