### ISSUE TITLE
Is Entry a buildin type?

### ISSUE THREAD

**Issue by linonetwo** [apollostack/GitHunt-API#45]
I fount some field returns [Entry] or Entry, but there is no type Entry definition.

Is Entry a new build in type or is a mistake?

https://github.com/apollostack/GitHunt-API/search?utf8=%E2%9C%93&q=Entry

**Comment by stubailo** [comment]
Looks like github search is just bad, look in here: https://github.com/apollostack/GitHunt-API/blob/106204c110980df28b70b565452a61648825d98b/api/sql/schema.js
