### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by felixb101** [apollostack/GitHunt-API#7]
git clone https://github.com/apollostack/GitHunt.git

should be 

git clone https://github.com/apollostack/GitHunt-API.git

...are you trying to confuse newbies?

**Comment by stubailo** [comment]
> ...are you trying to confuse newbies?

Definitely not, sorry! We just reorganized the repos and I forgot to update that part.

**Comment by stubailo** [comment]
https://github.com/apollostack/GitHunt-API/commit/83562ca7c18e65b110e9733a33b29268c6b2b92a
