### ISSUE TITLE
hotScore can be null

### ISSUE THREAD

**Issue by qcho** [apollostack/GitHunt-API#76]
Running [this query](http://localhost:3010/graphiql?query=%7B%0A%20%20entry%28repoFullName%3A%20%22apollostack%2Fapollo-client%22%29%20%7B%0A%20%20%20%20hotScore%0A%20%20%7D%0A%7D%0A)

```
{
  entry(repoFullName: "apollostack/apollo-client") {
    hotScore
  }
}
```

returns

```
{
  "data": {
    "entry": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Entry.hotScore.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

it seems the logic is returning null and the schema is not allowing it. I didn't create any pull request because i don't know if you want to fix the schema or the logic.

**Comment by kamilkisiela** [comment]
@qcho Try to remove `dev.sqlite3` file and then run:

```
npm run migrate
npm run seed
```
