### ISSUE TITLE
Make use of attachConnectorsToContext

### ISSUE THREAD

**Issue by tonyxiao** [apollostack/GitHunt-API#8]
It would be nice if we can make use of the official `graphql-tools` `attachConnectorsToContext` api. Seems that we manually construct context right now, which is fine, but it makes it unclear whether `attachConnectorsToContext` should be used or how it should be used.  

http://docs.apollostack.com/graphql-tools/connectors.html

**Comment by stubailo** [comment]
Do you think there is a benefit to use it?

**Comment by tonyxiao** [comment]
I'm honestly not sure, was just looking for example of where `attachConnectorsToContext` is best used.

**Comment by stubailo** [comment]
Personally I wouldn't use it - it's easy enough to just attach them yourself, and then it's much clearer what ends up on the context.

**Comment by tonyxiao** [comment]
Got it, what's the motivation for having it in the API then if you don't think it's actually a good idea to use it?

**Comment by helfer** [comment]
@tonyxiao good point. That API is actually something we're planning to remove with the next minor version bump, because it turned out not to be that useful.

**Comment by stubailo** [comment]
Thanks for the input, @helfer!
